// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdmfdjpaqvoggwbsgsje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkbWZkanBhcXZvZ2d3YnNnc2plIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNTIzMDMsImV4cCI6MjA2NTkyODMwM30.PxARaMCPkzUrTJwyPecY8YerBV8HJ-kGovhvEikOR1U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);